# Client:

GET http://localhost:3001/client/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE1ZWQ0NDgzYTZhYmJjOGM2YzIxODEiLCJpYXQiOjE2NzkxNTg2MDN9.wVuSGIdAmUI9llPBxO7nGdiu2bSuOzDTIn3SuI_L3kc
###
# Freelancer
GET http://localhost:3001/freelancer/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE0OWFhNDY5NDdkYWNjMjlmOGQ4MmUiLCJpYXQiOjE2Nzk1ODQyMTd9.3Raigkl7l61HFwpH536Yb5f_MjOHc5oa8ZgvAjUrCtk

# Tarik eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDBlMmZhNWQ5NjJhZmFjMDk0M2YxY2YiLCJpYXQiOjE2Nzk1MTA1MDZ9.i__rE84GOfI78yUmQe6gGqAuayqo1dOQNgZob9xrDqo

# Walid eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDFjNmEzNDI5ZWIxMzY1MDBiZGJlOWMiLCJpYXQiOjE2Nzk1ODM4MDR9.zcmm6VUxmyoKYTMtoUr8ZsabbcQxK3D09B91JTU-1bU

# Test eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE1ZWQ0NDgzYTZhYmJjOGM2YzIxODEiLCJpYXQiOjE2NzkxNTg2MDN9.wVuSGIdAmUI9llPBxO7nGdiu2bSuOzDTIn3SuI_L3kc

# Leo eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE0OWFhNDY5NDdkYWNjMjlmOGQ4MmUiLCJpYXQiOjE2Nzk1ODQyMTd9.3Raigkl7l61HFwpH536Yb5f_MjOHc5oa8ZgvAjUrCtk

